baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "_ws"

googleAnalytics = ""

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
